### PR TITLE
Update rate_my_app.podspec

### PR DESCRIPTION
**Pull request by shaun0203**
added swift version as pod install was not working without it

### CODE REVIEW

**Comment by Skyost** [comment]
Are you sure it wasn't working without that line ? Last time I tested, it worked without any error.

**Comment by shaun0203** [comment]
100 % sure, XCode 11.4.1

**Comment by shaun0203** [comment]
and latest flutter release

**Comment by shaun0203** [comment]
Plus it can’t hurt to have it as fail safe

**Comment by shaun0203** [comment]
Can you confirm if it can be merged?

**Pull request closed without merging**
