### PR TITLE
Migrate null safety

### PR DESCRIPTION
**Pull request by acoutts**

### CODE REVIEW

**Comment by Skyost** [comment]
Wow, thanks for this pull request ! Would it be possible for you to format it using `dartfmt` ?

**Comment by acoutts** [comment]
Done!

**Comment by Skyost** [comment]
Great !

**Comment by acoutts** [comment]
@Skyost please don't forget to publish it on pub too.

**Comment by Skyost** [comment]
I still need run some tests tbh.

**Comment by acoutts** [comment]
@Skyost any update on publishing the null safe version here?

**Comment by Skyost** [comment]
I'm a little bit busy currently because of my studies, but I will test it this week-end 😉

**Comment by Skyost** [comment]
Done !

**Pull request merged**
